baseURL = "https://kaspervaessen.github.io"
languageCode = "en-us"
title = "Career Orientation Days"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "logo/logo_kort_background.svg"
    mobile_height = "20px"
    mobile_width = "40px"
    desktop = "logo/logo_kort_background.svg"
    desktop_height = "20px"
    desktop_width = "40px"
    alt = "arrow"

  [params.homepage_meta_tags]
    meta_description = "The Career Orientation Days is an event where computer science and mathematics students have the chance one-on-one conversation with companies."
    meta_og_title = "Career Orientation Days"
    meta_og_type = "website"
    meta_og_url = "https://cod.ch.tudelft.nl"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "The Career Orientation Days is an event where computer science and mathematics students have the chance one-on-one conversation with companies."


[[menu.main]]
    identifier = "Companies"
    name = "Companies"
    url="/companies/"
    weight = 1

[[menu.main]]
    name = "Mathematics"
    url = "/companies/mathematics/"
    parent = "Companies"
    weight = 1

[[menu.main]]
    name = "Computer Science"
    url = "/companies/computer_science/"
    parent = "Companies"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[[menu.main]]
    name = "Register"
    url = "/registration/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
